[[window]]
name = "nvim"
startup_script = "nvim"

[[window]]
name = "cmd"
startup_script = "git status"


[[wildcard]]
pattern = "~/Projects/*"
startup_command = "git status"
preview_command = "eza --all --git --icons --color=always {}"
windows = ["nvim", "cmd"]

[[session]]
name = "Home"
startup_command = "fastfetch"
preview_command = "fastfetch"
path = "~"

[[session]]
name = "Dotfiles"
startup_command = "git status"
preview_command = "eza --all --git --icons --color=always {}"
path = "~/.dotfiles"
windows = ["nvim", "cmd"]
