[[window]]
name = "nvim"
startup_script = "nvim"

[[window]]
name = "cmd"
startup_script = "git status"


[[wildcard]]
pattern = "~/Projects/*"
windows = ["nvim", "cmd"]

# [[session]]
# name = "Home"
# path = "~"
#
# [[session]]
# name = "Dotfiles"
# path = "~/.dotfiles"
# windows = ["nvim", "cmd"]
