set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g prefix C-a

set -g base-index 1
set -g renumber-windows on
set -g status-style bg=default,fg=#c0caf5
set -g status-left ""
set -g status-right "#[fg=#c0caf5]#S"
set -g window-status-separator ""
set -g window-status-format " #[fg=#565f89]● "
set -g window-status-current-format " #[fg=magenta]● "

set -g window-status-current-style "nobold"
set -g window-status-bell-style "fg=red,nobold"

setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

set -g mouse on
set -g history-limit 10000
set -g set-clipboard on
set -g escape-time 0

set -g status-left-length 0


bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

bind-key "T" display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' tv sesh
bind-key x kill-pane
set -g detach-on-destroy off 

run '~/.tmux/plugins/tpm/tpm'
