set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g prefix C-a

set -g base-index 1
set -g renumber-windows on
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

set -g mouse on
set -g history-limit 10000
set -g set-clipboard on
set -g escape-time 0

set -g status-left-length 0


bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

bind-key "T" display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' tv sesh
bind-key x kill-pane
set -g detach-on-destroy off 

set -g extended-keys on

RED="#f7768e"
GREEN="#9ece6a"
YELLOW="#e0af68"
BLUE="#7aa2f7"
PURPLE="#bb9af7"
CYAN="#7dcfff"
BG="#24283b"
BG_ALT="#1f2335"
FG="#c0caf5"
FG_ALT="#a9b1d6"

SEPARATOR="#(printf '\uE0BF')"
TRIANGLE_OPEN="#(printf '\uE0BE')"
TRIANGLE_CLOSE="#(printf '\uE0B8')"

set -g status-style bg=${BG},fg=${FG}
set -g status-justify absolute-centre


set -g status-left "\
#[bg=${BG_ALT},fg=${FG_ALT}] #S \
#[fg=${BG_ALT},bg=default]${TRIANGLE_CLOSE}\
"
set -g status-right ""
set -g status-left-length 100
set -g status-right-length 100

set -g window-status-format "\
#[fg=${BG_ALT},bg=default]${TRIANGLE_OPEN}\
#[bg=${BG_ALT},fg=${FG}] #I\
#[bg=${BG_ALT},fg=${BG}] ${SEPARATOR} \
#[fg=default]#W\
 \
#[fg=${BG_ALT},bg=default]${TRIANGLE_CLOSE}\
"

set -g window-status-current-format "\
#[fg=${BG_ALT},bg=default]${TRIANGLE_OPEN}\
#[bg=${BG_ALT},fg=${PURPLE}] #I\
#[bg=${BG_ALT},fg=${BG}] ${SEPARATOR} \
#[fg=default]#W\
 \
#[fg=${BG_ALT},bg=default]${TRIANGLE_CLOSE}\
"


run '~/.tmux/plugins/tpm/tpm'
